<?php
/**
 * Available fonts options
 *
 * @category   Wordspop
 * @package    WPop
 * @copyright  Copyright (c) 2010-2011 Wordspop
 * @license    http://www.opensource.org/licenses/gpl-2.0.php GNU GPL version 2
 * @version    $Id:$
 */
$GLOBALS['wpop_fonts'] = array(

    ''                                                                            => 'Default...',

    // Web-safe fonts
    'Arial, sans-serif'                                                           => 'Arial',
    '"Arial Black", sans-serif'                                                   => 'Arial Black',
    'Calibri, Candara, Segoe, Optima, sans-serif'                                 => 'Calibri',
    '"Gill Sans", "Gill Sans MT", Calibri, sans-serif'                            => 'Gill Sans',
    'Geneva, Tahoma, Verdana, sans-serif'                                         => 'Geneva',
    'Georgia, serif'                                                              => 'Georgia',
    '"Helvetica Neue", Helvetica, sans-serif'                                     => 'Helvetica',
    'Impact, Charcoal, sans-serif'                                                => 'Impact',
    '"Lucida Grande", "Lucida Sans Unicode", "Lucida Sans", sans-serif'           => 'Lucida Grande',
    '"Myriad Pro", Myriad, sans-serif'                                            => 'Myriad Pro',
    'Tahoma, Geneva, Verdana, sans-serif'                                         => 'Tahoma',
    '"Times New Roman", serif'                                                    => 'Times New Roman',
    '"Trebuchet MS", Tahoma, sans-serif'                                          => 'Trebuchet',
    'Palatino, "Palatino Linotype", serif'                                        => 'Palatino',
    'Verdana, Geneva, sans-serif'                                                 => 'Verdana',

    'google'                                                                      => '-- Google Web Fonts --',

    // Google Web Fonts
    'google: Allan, Arial, serif'                                                 => 'Allan',
    'google: Allerta, Georgia, "Times New Roman", Arial, serif'                   => 'Allerta',
    'google: "Allerta Stencil, Georgia, "Times New Roman", Arial, serif"'         => 'Allerta Stencil',
    'google: "Anonymous Pro", Geneva, Verdana, serif'                             => 'Anonymous Pro',
    'google: Anton, Georgia, "Times New Roman", Arial, serif'                     => 'Anton',
    'google: Arimo, Georgia, "Times New Roman", Arial, serif'                     => 'Arimo',
    'google: Arvo, Georgia, "Times New Roman", Arial, serif'                      => 'Arvo',
    'google: Astloch, Georgia, "Times New Roman", Arial, serif'                   => 'Astloch',
    'google: Bentham, Georgia, "Times New Roman", Arial, serif'                   => 'Bentham',
    'google: Bevan, Georgia, "Times New Roman", Arial, serif'                     => 'Bevan',
    'google: Buda, Georgia, "Times New Roman", Arial, serif'                      => 'Buda',
    'google: Cabin, Georgia, "Times New Roman", Arial, serif'                     => 'Cabin',
    'google: Calligraffitti, Georgia, "Times New Roman", Arial, serif'            => 'Calligraffitti',
    'google: Cantarell, Georgia, "Times New Roman", Arial, serif'                 => 'Cantarell',
    'google: Cardo, Georgia, "Times New Roman", Arial, serif'                     => 'Cardo',
    'google: "Cherry Cream Soda", Georgia, "Times New Roman", Arial, serif'       => 'Cherry Cream Soda',
    'google: Chewy, Georgia, "Times New Roman", Arial, serif'                     => 'Chewy',
    'google: Coda, Georgia, "Times New Roman", Arial, serif'                      => 'Coda',
    'google: "Coming Soon", Georgia, "Times New Roman", Arial, serif'             => 'Coming Soon',
    'google: Copse, Georgia, "Times New Roman", Arial, serif'                     => 'Copse',
    'google: Corben, Georgia, "Times New Roman", Arial, serif'                    => 'Corben',
    'google: Cousine, Georgia, "Times New Roman", Arial, serif'                   => 'Cousine',
    'google: "Covered By Your Grace", Georgia, "Times New Roman", Arial, serif'   => 'Covered By Your Grace',
    'google: "Crafty Girls", Georgia, "Times New Roman", Arial, serif'            => 'Crafty Girls',
    'google: "Crimson Text", Georgia, "Times New Roman", Arial, serif'            => 'Crimson Text',
    'google: Crushed, Georgia, "Times New Roman", Arial, serif'                   => 'Crushed',
    'google: Cuprum, Georgia, "Times New Roman", Arial, serif'                    => 'Cuprum',
    'google: "Dancing Script", Georgia, "Times New Roman", Arial, serif'          => 'Dancing Script',
    'google: "Droid Sans", Georgia, "Times New Roman", Arial, serif'              => 'Droid Sans',
    'google: "Droid Sans Mono", Georgia, "Times New Roman", Arial, serif'         => 'Droid Sans Mono',
    'google: "Droid Serif", Georgia, "Times New Roman", Arial, serif'             => 'Droid Serif',
    'google: "Expletus Sans", Georgia, "Times New Roman", Arial, serif'           => 'Expletus Sans',
    'google: "Fontdiner Swanky", Georgia, "Times New Roman", Arial, serif'        => 'Fontdiner Swanky',
    'google: Geo, Georgia, "Times New Roman", Arial, serif'                       => 'Geo',
    'google: "Goudy Bookletter 1911", Georgia, "Times New Roman", Arial, serif'   => 'Goudy Bookletter 1911',
    'google: Gruppo, Georgia, "Times New Roman", Arial, serif'                    => 'Gruppo',
    'google: "Homemade Apple", Georgia, "Times New Roman", Arial, serif'          => 'Homemade Apple',
    'google: "IM Fell", Georgia, "Times New Roman", Arial, serif'                 => 'IM Fell',
    'google: Inconsolata, "Myriad Pro", Geneva, Arial, serif'                     => 'Inconsolata',
    'google: "Irish Growler", Georgia, "Times New Roman", Arial, serif'           => 'Irish Growler',
    'google: "Josefin Sans", Georgia, "Times New Roman", Arial, serif'            => 'Josefin Sans',
    'google: "Josefin Slab", Georgia, "Times New Roman", Arial, serif'            => 'Josefin Slab',
    'google: "Just Another Hand", Georgia, "Times New Roman", Arial, serif'       => 'Just Another Hand',
    'google: "Just Me Again Down Here", Georgia, "Times New Roman", Arial, serif' => 'Just Me Again Down Here',
    'google: Kenia, Georgia, "Times New Roman", Arial, serif'                     => 'Kenia',
    'google: Kranky, Georgia, "Times New Roman", Arial, serif'                    => 'Kranky',
    'google: Kreon, Georgia, "Times New Roman", Arial, serif'                     => 'Kreon',
    'google: Kristi, Georgia, "Times New Roman", Arial, serif'                    => 'Kristi',
    'google: Lato, Georgia, "Times New Roman", Arial, serif'                      => 'Lato',
    'google: Lekton, Georgia, "Times New Roman", Arial, serif'                    => 'Lekton',
    'google: Lobster, Georgia, "Times New Roman", Arial, serif'                   => 'Lobster',
    'google: "Luckiest Guy", Georgia, "Times New Roman", Arial, serif'            => 'Luckiest Guy',
    'google: Meddon, Georgia, "Times New Roman", Arial, serif'                    => 'Meddon',
    'google: Merriweather, Georgia, "Times New Roman", Arial, serif'              => 'Merriweather',
    'google: Molengo, Georgia, "Times New Roman", Arial, serif'                   => 'Molengo',
    'google: "Mountains of Christmas", Georgia, "Times New Roman", Arial, serif'  => 'Mountains of Christmas',
    'google: Neucha, Georgia, "Times New Roman", Arial, serif'                    => 'Neucha',
    'google: Neuton, Georgia, "Times New Roman", Arial, serif'                    => 'Neuton',
    'google: Nobile, Georgia, "Times New Roman", Arial, serif'                    => 'Nobile',
    'google: "OFL Sorts Mill Goudy TT", Georgia, "Times New Roman", Arial, serif' => 'OFL Sorts Mill Goudy TT',
    'google: "Old Standard TT", Georgia, "Times New Roman", Arial, serif'         => 'Old Standard TT',
    'google: Orbitron, Georgia, "Times New Roman", Arial, serif'                  => 'Orbitron',
    'google: "PT Sans", Georgia, "Times New Roman", Arial, serif'                 => 'PT Sans',
    'google: "PT Serif", Georgia, "Times New Roman", Arial, serif'                => 'PT Serif',
    'google: "Permanent Marker", Georgia, "Times New Roman", Arial, serif'        => 'Permanent Marker',
    'google: Philosopher, Georgia, "Times New Roman", Arial, serif'               => 'Philosopher',
    'google: Puritan, Georgia, "Times New Roman", Arial, serif'                   => 'Puritan',
    'google: Radley, Georgia, "Times New Roman", Arial, serif'                    => 'Radley',
    'google: Raleway, Georgia, "Times New Roman", Arial, serif'                   => 'Raleway',
    'google: "Reenie Beanie", Georgia, "Times New Roman", Arial, serif'           => 'Reenie Beanie',
    'google: "Rock Salt", Georgia, "Times New Roman", Arial, serif'               => 'Rock Salt',
    'google: Schoolbell, Georgia, "Times New Roman", Arial, serif'                => 'Schoolbell',
    'google: Slackey, Georgia, "Times New Roman", Arial, serif'                   => 'Slackey',
    'google: Sniglet, Georgia, "Times New Roman", Arial, serif'                   => 'Sniglet',
    'google: Sunshiney, Georgia, "Times New Roman", Arial, serif'                 => 'Sunshiney',
    'google: Syncopate, Georgia, "Times New Roman", Arial, serif'                 => 'Syncopate',
    'google: Tangerine, Georgia, "Times New Roman", Arial, serif'                 => 'Tangerine',
    'google: Tinos, Georgia, "Times New Roman", Arial, serif'                     => 'Tinos',
    'google: Ubuntu, Georgia, "Times New Roman", Arial, serif'                    => 'Ubuntu',
    'google: UnifrakturCook, Georgia, "Times New Roman", Arial, serif'            => 'UnifrakturCook',
    'google: UnifrakturMaguntia, Georgia, "Times New Roman", Arial, serif'        => 'UnifrakturMaguntia',
    'google: Unkempt, Georgia, "Times New Roman", Arial, serif'                   => 'Unkempt',
    'google: VT323, Georgia, "Times New Roman", Arial, serif'                     => 'VT323',
    'google: Vibur, Georgia, "Times New Roman", Arial, serif'                     => 'Vibur',
    'google: Vollkorn, Georgia, "Times New Roman", Arial, serif'                  => 'Vollkorn',
    'google: "Walter Turncoat", Georgia, "Times New Roman", Arial, serif'         => 'Walter Turncoat',
    'google: "Yanone Kaffeesatz", Georgia, "Times New Roman", Arial, serif'       => 'Yanone Kaffeesatz'

);
